### ISSUE TITLE
Talend Open Studio 7.3.1 no longer available for download

### ISSUE THREAD

**Issue by killertilapia** [openpim/talend#2]
Talend has been [acquired by Qlik](https://www.talend.com/about-us/press-releases/qlik-completes-acquisition-of-talend/) last May 16, 2023 and removed access to the 7.3.1 version of TOS. We have no choice but download version 8.0.1.

I tried installing OpenPIM integration as [per documentation](https://www.openpim.org/docs/admin/guide/02_ImportExport.html#introduction) just to see. No dice.

**Comment by openpim** [comment]
Hi @killertilapia,

Sorry, it was a link to outdated documentation on our site. The right document is https://openpim.org/university/import_export
Out components fully support Talend 8.0.1 so you should not have problems with them.

If you want we can organize a call and I can help you to resolve this issue. Please send an email to team@openpim.org

Thanks,
Slava Pedak
