### ISSUE TITLE
Error importing component OpenPim

### ISSUE THREAD

**Issue by borisdagnon** [openpim/talend#3]
Hi,
I imported the OpenPim components with the following command:
`java -jar pim-components.car studio-deploy <DIRECTORY WHERE Talend IS INSTALLED>`
but i get an error when restarting Talend.
![image](https://github.com/openpim/talend/assets/16353265/733a2cbd-3567-4aff-a26f-13cf71dd00fe)

**Comment by openpim** [comment]
Hi @borisdagnon,

Can you please clarify what Talend version you are using? If you are using Talend 8 please make sure that you are using java version 11 (this is quite old version) instead of something else because Talend requires java 11.

Thanks,
Slava Pedak

**Comment by borisdagnon** [comment]
Hi,
I'm using the version 8.0.1.20211109_1610 of Talend.
And i specified the version 11 of Java in the config.
![image](https://github.com/openpim/talend/assets/16353265/7d1f0886-f7d2-4fd7-86c5-1a1b37cedac4)

Thanks.

**Comment by openpim** [comment]
Hi @borisdagnon,

But what jdk are you using to start Talend? You should take a look into TOS_DI-win-x86_64.ini file.
You can specify the java version there like

-vm
C:\Program Files\Java\jdk-11.0.16.1\bin
-vmargs
-Xms512m
-Xmx1536m
...

Thanks,
Slava Pedak

**Comment by borisdagnon** [comment]
Hi @openpim 
That's how it looks like now.
![image](https://github.com/openpim/talend/assets/16353265/e01eddda-1def-453a-b168-bb81108ed284)

**Comment by borisdagnon** [comment]
Sorry,
This is what i'm having now.
![image](https://github.com/openpim/talend/assets/16353265/96286655-4aa4-4020-bdeb-4480ad46228c)

**Comment by borisdagnon** [comment]
> Sorry, This is what i'm having now. ![image](https://user-images.githubusercontent.com/16353265/272589280-96286655-4aa4-4020-bdeb-4480ad46228c.png)

I found the source of the error.
After addind what you told me, my also added the env variable JAVA in windows, adn now it's working.
Thanks

**Comment by openpim** [comment]
Hi, 

The path C:\Program Files\Java\jdk-11.0.16.1\bin is just an example, this is path I have at my computer. You should provide your real path there.

Thanks,
Slava Pedak
